$(function () {
  $('#{{ element_id }}').highcharts({
    chart: {
      type: 'column'
    },
    credits: false,
    title: {
      text: '{{ chart.title() | to_human }}'
    },
    subtitle: {
      text: 'Generated by Pivotal Stocks'
    },
    xAxis: {
      categories: {{ chart.categories() | to_json }}
    },
    yAxis: {
      min: 0,
      title: {
        text: '{{ chart.y_title() | to_human }}'
      }
    },
    tooltip: {
      headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
      pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
      '<td style="padding:0"><b>{point.y:.2f}</b></td></tr>',
      footerFormat: '</table>',
      shared: true,
      useHTML: true
    },
    plotOptions: {
      column: {
        pointPadding: 0.2,
        borderWidth: 0
      }
    },
    series: {{ chart.series() | to_json }}
  });
});
